### ISSUE TITLE
Tokenize doesn't work with list of unary hands.

### ISSUE THREAD

**Issue by atte-backman** [npiv/joldem#1]
When trying to tokenize for example this:

[ "AsQs", "AcQc", "AdQd", "AhQh", "AsQc", "AsQd", "AsQh", "AcQs", "AcQd", "AcQh", "AdQs", "AdQc", "AdQh", "AhQs", "AhQc", "AhQd", "AsKs", "AcKc", "AdKd", "AhKh", "AsKc", "AsKd", "AsKh", "AcKs", "AcKd", "AcKh", "AdKs", "AdKc", "AdKh", "AhKs", "AhKc", "AhKd" ]

the result is empty string, where it should be AQ+.

**Comment by npiv** [comment]
Thanks for reporting.

Fixed in 1.0.4
